# Generated by Django 2.1.5 on 2019-01-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190112_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='article.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='high_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hcate', to='article.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
