# Generated by Django 2.1.5 on 2019-01-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190112_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nickname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='article.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='high_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hcate', to='article.Category'),
        ),
    ]
